{% set name = "climatecontrol" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/climatecontrol-{{ version }}.tar.gz
  sha256: ad2f8da62eb1dd6cae4d4721c8b6628484d8d1cdccb780cfe047fe53dc50604d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0,<2.0.0
    - pytest-runner
  run:
    - python >={{ python_min }}
    - wrapt

test:
  imports:
    - climatecontrol
    - climatecontrol.ext
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/daviskirk/climatecontrol
  summary: Python library for loading app configurations from files and/or namespaced environment variables
  description: |
    CLIMATECONTROL controls your applications settings and configuration environment. It is a Python library for loading app configurations from files and/or namespaced environment variables.

    Features
      * Separation of settings and code
      * Loading from files (.yaml, .json, .toml)
      * Loading multiple files using glob syntax
      * Loading from environment variables, including loading of nested values
      * Freely reference nested configurations via files or environment variables
      * CLI integration
      * Validation using the Validation library of your choice
      * Logging configuration integration
      * Testing integration
  dev_url: https://github.com/daviskirk/climatecontrol
  doc_url: https://github.com/daviskirk/climatecontrol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daviskirk
